### ISSUE TITLE
Channel not showing on Plex

### ISSUE THREAD

**Issue by asb2106** [shopgirl284/MTVNetworks.bundle#5]
I have added the appstore, and added a request channel with it, worked great.  When i add this channel everything works the way it should, however it doesn't show in Plex.  I am hoping its something simple I looked over? Any help is really appreciated! Thanks

**Comment by asb2106** [comment]
I have rebooted the PMS and whole machine with no luck.

**Comment by shopgirl284** [comment]
First, reboot Plex Media Server after installation. Sometimes you must reboot PMS for it to load all the files necessary to recognize the channel.

Otherwise, how did you install this channel? If you used the UASv2 plugin, you would need to refer to the support thread for UASv2 to troubleshoot issues with its installation of channel plugins.

If you manually installed the plugin, see https://support.plex.tv/hc/en-us/articles/201187656-How-do-I-manually-install-a-channel- and https://support.plex.tv/hc/en-us/articles/201187666-Why-isn-t-the-channel-bundle-I-installed-showing-up-in-Plex- for instructions and common errors and issues with a manual installation.

Also be aware that the SheildTV does not allow manual installation of channel plugins when it used as a Plex Media Server.

**Comment by asb2106** [comment]
I was able to get it.  I removed the UAS install and DLed copied over from here and it went right up.  Thanks for the help.

**Comment by shopgirl284** [comment]
Glad it works now
